### ISSUE TITLE
{Request} Enjoyment Ratings

### ISSUE THREAD

**Issue by MasterGamerY** [B1rtek/Geode-GDDLIntegration#1]
In addition to tier ratings, maybe you could add the enjoyment rating of the demon below the tier.

**Comment by B1rtek** [comment]
That's exactly what I'm planning for the next update 👍

**Comment by B1rtek** [comment]
https://github.com/B1rtek/Geode-GDDLIntegration/pull/3 adds this, it's already merged into master, should come out soon
