### ISSUE TITLE
Tier text overlaps diamond counter on weekly demons.

### ISSUE THREAD

**Issue by KaydaCant** [B1rtek/Geode-GDDLIntegration#10]
**Describe the bug**
On the weekly demon page, the tier counter will overlap the diamond counter for the level causing this ugly mess.
![image](https://github.com/B1rtek/Geode-GDDLIntegration/assets/97423855/73309a59-448a-45b5-9270-a75231fb8bea)

**To Reproduce**
Open the weekly demon page. Voila.

EDIT: NVM was so busy getting mad at github login that i forgot to check if the mod had updates. oops.

**Comment by B1rtek** [comment]
Update the mod :) it's fixed already in v1.0.2
