### ISSUE TITLE
Pressing one of 

### ISSUE THREAD

**Issue by Flyingturtle215** [B1rtek/Geode-GDDLIntegration#17]
Platform: Windows
v1.0.5

When pressing one of the numbers on the "GDDL Demon Split" menu on your profile, the game crashes after trying to pull up a page of levels
![image](https://github.com/B1rtek/Geode-GDDLIntegration/assets/91761140/4c60aff1-a956-4797-896d-7251b9bc65b8)
![image](https://github.com/B1rtek/Geode-GDDLIntegration/assets/91761140/cbe70841-8a98-4092-9185-47e93612fafc)

1. Go to your profile from the GD main menu
2. Click on the question mark button next to your demon count
![image](https://github.com/B1rtek/Geode-GDDLIntegration/assets/91761140/5ac501f3-0940-4331-a8a6-e1a2f674af4b)
3. Game will crash trying to pull up a page of levels

Crash Log
[2024-02-11_20-39-33.log](https://github.com/B1rtek/Geode-GDDLIntegration/files/14234907/2024-02-11_20-39-33.log)

Have a few profile-altering mods installed that might be affecting the mod in this way

I have the latest version of the mod installed

**Comment by B1rtek** [comment]
This is caused by a bug in Redlime's Stat Changes mod, [I opened an issue regarding that](https://github.com/RedLime/Stat-Changes-Geode/issues/1) in that mod's repository, but the creator didn't respond yet.

**Comment by B1rtek** [comment]
There are currently two workarounds for that - either disable the Stat Changes mod or always wait for the stat changes to load before entering the GDDL Demon Split submenu

**Comment by B1rtek** [comment]
It's fixed in the newest update of Stat Changes 👍
