### ISSUE TITLE
I don't like the new search

### ISSUE THREAD

**Issue by GKoble** [B1rtek/Geode-GDDLIntegration#21]
Hi !

First i gotta say that you guys are doing an amazing job and this mod is probably the most useful one i use !

However you changed a lot the search feature and I think it traded the simplicity for features that are straight up useless for me, it's just 100x more annoying to search for a singular tier which is literally the only thing i'm looking for. I loved the old search feature, can you add a setting which would allow us to use the old search buttons ?

Thanks for reading and thanks a lot for this mod :D

Koble.

**Comment by B1rtek** [comment]
Ok 🥴
