### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Helloausername** [B1rtek/Geode-GDDLIntegration#26]
the gddl search cant be open with the mod integrated demonlist and the integrated demonlist button is hidden by the gddl search button

both of mods latest version

device android 32bit

**Comment by B1rtek** [comment]
![Screenshot_2024-02-27-17-03-27-57_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/B1rtek/Geode-GDDLIntegration/assets/53182944/ec88ca0e-27cd-4c36-8a64-a4c58951e3d7)

![Screenshot_2024-02-27-17-03-42-71_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/B1rtek/Geode-GDDLIntegration/assets/53182944/dcd8d918-e5fb-4d46-920b-5e2bede6734d)

![Screenshot_2024-02-27-17-03-53-22_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/B1rtek/Geode-GDDLIntegration/assets/53182944/b4f38b35-fbeb-4529-9101-fb9dd2205d7a)

Doing that should fix the issue (it's quite weird that the integrated demon list button has a higher touch priority even though it's under the gddl search button)

**Comment by B1rtek** [comment]
I'm going to assume that it worked since you haven't responded saying that it doesn't and close this issue tomorrow
