### ISSUE TITLE
kezboard inout x search bug (very annoying)

### ISSUE THREAD

**Issue by GlassesCatandsteve** [B1rtek/Geode-GDDLIntegration#27]
**Describe the bug**

When doing the following things
1 : typing a value in the enjoyment rating (dont know if this applies to the other textboxes) with your keyboard
2 : playing one of the searched levels

basically , in your code you forgot to implement a function that closes the gddl filter menu / exits zou out of the textbox , so when you play a level(which you searched for with the gddl filter) after typing in a value with your keyboard (as described above) all keyboard inputs still get sent to the textbox , so while playing the level , if you press eg. the spacebar to jump , it types a space in the textbox of the filter menu (as described above) . should be an easy fix (idk if it is , i am a programmer but dont know c++)

**To Reproduce**

1. go to the online search tab
2. click on the red question mark button
3. type any value into the enjoyment textbox with your keyboard
4. search up a level with that value via your filter
5. play the level
6. try to make a keyboard input
7. see error (after leaving the level gd crashes alot of the times)

[2024-03-02_12-25-35.log](https://github.com/B1rtek/Geode-GDDLIntegration/files/14469153/2024-03-02_12-25-35.log)
[2024-03-02_12-27-41.log](https://github.com/B1rtek/Geode-GDDLIntegration/files/14469155/2024-03-02_12-27-41.log)

**Additional context**
none
**I checked that I have the latest version of this mod**
Yes

please fix this ASAP :)

**Comment by B1rtek** [comment]
Interesting, I can see why it could happen but I can't replicate the crash. I'll take care of it anyway because you probably shouldn't be able to input stuff into a textbox that you can't see

**Comment by GlassesCatandsteve** [comment]
yea , ty , you cant replicate the crash or the issue

B1rtek ***@***.***> schrieb am Mo., 4. März 2024, 13:02:

**Comment by B1rtek** [comment]
The crash, I am able to type into the search textboxes though

**Comment by B1rtek** [comment]
There's a high chance that this is fixed by the new patch, stoi() shouldn't crash the game anymore and you get automatically clicked off from all text input fields, but I can't know that for sure since I never managed to replicate your crashes

**Comment by GlassesCatandsteve** [comment]
weird  , anyways thank you , the main issue was the input anyways

B1rtek ***@***.***> schrieb am Fr., 8. März 2024, 21:01:

**Comment by B1rtek** [comment]
https://github.com/B1rtek/Geode-GDDLIntegration/releases/download/v1.1.3/b1rtek.gddlintegration.geode here's a link to the newest release, you can also just wait for it to be uploaded to the geode mod index
