### ISSUE TITLE
(Android64) Crash when entering the tier lists of uncompleted/completed demon levels

### ISSUE THREAD

**Issue by HotKentang** [B1rtek/Geode-GDDLIntegration#29]
**Describe the bug**
A bug when if you open up the game and immediately go inside the demonlist search tab & press the tier list button with one of the checkboxes is on (either uncompleted/completed), you will crash after doing that.

**To Reproduce**
1. Go to 'search tab of demonlist' immediately after opening up the game
2. Click on 'go to the other page (where there are many tier list buttons from tier 1 — 35)'
3. Make sure to tick one of the checkboxes (either completed or uncompleted, pick one)
4. Go to tier list 2 or any tier lists
5. Error

https://github.com/B1rtek/Geode-GDDLIntegration/assets/161263883/a10ab9f2-5f3b-4611-84ca-7255220828fc

**
[Crash 2024-03-09 11.45.17.dmp](https://github.com/B1rtek/Geode-GDDLIntegration/files/14545007/Crash.2024-03-09.11.45.17.dmp)
**

**Additional context**
I am using geode nightly version 709a6a3, I don't know if this bug also applies to the original geode ver., But what I do know is that this bug had never happened until the mod got updated today.

**I checked that I have the latest version of this mod**
Yes

**Comment by B1rtek** [comment]
I got a similar report from another user on Windows, I'm looking into it

**Comment by B1rtek** [comment]
I think I know what the exact issue of this is rn, there's a workaround you can use: switch to the full search interface and back into the simple one before searching for a tier

**Comment by B1rtek** [comment]
Fix here: https://github.com/B1rtek/Geode-GDDLIntegration/releases/download/v1.1.4/b1rtek.gddlintegration.geode
