### ISSUE TITLE
Game Crash When Clicking the Search Filter Button

### ISSUE THREAD

**Issue by Neonyx27** [B1rtek/Geode-GDDLIntegration#40]
Game Crash When Clicking the Search Filter Button

**To Reproduce**
1. Go to the search menu
2. Click on the gddl integration search filter button

**Crash log (from `Geometry Dash/geode/crashlogs`)**
2024-05-01T17:18:15-0400

Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.25
Loader Commit: 20dc3c9
Bindings Commit: 2eb85b0
Installed mods: 58
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 03987DBD (Geode.dll + 37dbd (cocos2d::CCNode::getChildByID + 45 | D:\a\geode\geode\loader\src\hooks\GeodeNodeMetadata.cpp:126))
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 37dbd (cocos2d::CCNode::getChildByID + 45 | D:\a\geode\geode\loader\src\hooks\GeodeNodeMetadata.cpp:126)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 3804a (cocos2d::CCNode::getChildByIDRecursive + 58 | D:\a\geode\geode\loader\src\hooks\GeodeNodeMetadata.cpp:135)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 118f5
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + c4b5
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 17e8e
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 37f25
 - 1B912F49
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\techstudent10.button_sfx\techstudent10.button_sfx.dll + 1a2d
 - 1B912B6B

== Register States ==
EAX: 009af13c
EBX: 00000001
ECX: 00000000
EDX: 009af174
EBP: 009af154
ESP: 009af100
EDI: 009af198
ESI: 00000000
EIP: 03987dbd

== Installed Mods ==
x | [v1.0.5] abb2k.backup
x | [v1.2.9] alphalaneous.deathlink
x | [v1.1.2] alphalaneous.projectedstars
x | [v1.0.2] alphalaneous.random_tab
x | [v1.1.6] b1rtek.gddlintegration
x | [v1.0.4] bitz.moregames
x | [v1.1.4] capeling.demons_in_garage_2.2
x | [v1.0.4] cdc.level_thumbnails
x | [v1.2.0] coopeeo.hideplus
x | [v4.1.10] cvolton.betterinfo
x | [v1.1.3] cvolton.misc_bugfixes
x | [v1.3.7] dankmeme.globed2
  | [v2.1.0] devcmb.cleanermenu
x | [v1.3.1] elsai.a_daily_shop
x | [v1.0.4] firee.GoldenBest
x | [v0.0.3] flafy.autonong
x | [v2.7.1] fleym.nongd
x | [v1.5.6] geode.custom-keybinds
x | [v2.0.0-beta.25] geode.loader
x | [v1.9.1] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v1.4.5] hiimjustin000.integrated_demonlist
x | [v6.3.3] hjfod.betteredit
x | [v1.0.5] hjfod.gdshare
x | [v1.0.5] hjfod.gmd-api
x | [v1.1.0] itzkiba.better_progression
x | [v1.0.2] itzkiba.elegant_rankings
x | [v1.1.0] itzkiba.grandpa_demon
x | [v1.2.0] khronophobia.shortcuts_menu
x | [v1.0.1] mat.max-window
x | [v1.1.0] mat.scroll-zoom
x | [v1.0.0-beta.19] minemaker0430.gddp_integration
x | [v1.1.1] mishpro.comments_in_pause_menu
x | [v1.2.0] ml5.treasure-checklist
x | [v1.1.1] ninkaz.blending_glow
x | [v1.2.5] nytelyte.wave_trail_drag_fix
x | [v1.1.1] petitfrapo.nomoregrayfilter
x | [v1.0.0] raydeeux.junkhider
x | [v1.3.0] raydeeux_thesillydoggo.evenmoreleveltags
x | [v1.1.1] redlime.statchanges
x | [v1.0.2] relative.account_statuses
x | [v1.0.1] relative.advanced_song_search
x | [v1.0.0] relative.scroll_faster_with_ctrl
x | [v0.1.1] rooot.pipebomb
x | [v1.1.0] rynat.better_unlock_info
x | [v1.1.0] techstudent10.button_sfx
x | [v1.0.1] thesillydoggo.animatedprofiles
x | [v1.0.0-beta.7] thesillydoggo.comment_emojis
x | [v1.6.9] thesillydoggo.entersearch
x | [v1.0.3] thesillydoggo.icon_kit_switcher
x | [v1.6.8] tpdea.betterpause-Better
x | [v1.1.0] uproxide.autosong
x | [v1.1.2] uproxide.geodedevelopers
x | [v1.3.0] uproxide.more_difficulties
x | [v1.0.3] weebify.level_info_in_pause_menu
x | [v1.0.4] xanii.youtubers
x | [v2.0.0] yellowcat98.profilebio
x | [v1.0.1] zilko.fps_counter

**I checked that I have the latest version of this mod**
Yes

**Comment by B1rtek** [comment]
This crash seems to occur at random, which is pretty weird, I'm pretty sure it's the same as the one I'm thinking of in #39
For now, try to uninstall and reinstall the mod, that should fix it for some reason
