### ISSUE TITLE
Wrong Button Used for Hyperlink

### ISSUE THREAD

**Issue by Aktimoose** [B1rtek/Geode-GDDLIntegration#46]
**Describe the bug**
The button used here is the undo button but flipped, for some reason
![image](https://github.com/B1rtek/Geode-GDDLIntegration/assets/44620677/98aef85c-15c3-429b-9dc6-cbb8060f5af9)
This does not fit with GD's design language, as the gradient is on the wrong side.

There is a redo button that exists in the game that would make much more sense
![image](https://github.com/B1rtek/Geode-GDDLIntegration/assets/44620677/31b6b45f-7003-45ec-9780-8a3e7bfc9cb8)

**I checked that I have the latest version of this mod**
Yes

**Comment by B1rtek** [comment]
You're right.

**Comment by B1rtek** [comment]
Also sorry for taking so long to respond, I'm extremely busy with my university projects so GDDL Int has to wait for now :/
