### ISSUE TITLE
Profile tiers do not work and appear as 0

### ISSUE THREAD

**Issue by python-nerd-3** [B1rtek/Geode-GDDLIntegration#47]
**Describe the bug**
When opening the menu on your profile that shows the tiers of all the demons you have completed, it shows up as if you have not completed any demons. I have completed 50 classic demons, yet nothing shows up in any of the tiers. Clicking on the icons to search shows an empty list.

![image](https://github.com/B1rtek/Geode-GDDLIntegration/assets/117922845/08da4fbb-7bb0-47d8-8b24-963dd17add04)

**To Reproduce**
1. Go to your profile
2. Click on the [?] icon

**Additional context**
I am using Windows 11.
I have 30 other mods installed and active (I can send you the list if you would like).

**I checked that I have the latest version of this mod**
Yes

**Comment by B1rtek** [comment]
it is possible that your ratings cache is corrupted, try removing gddlcache.json from the mod save files (somewhere under %LOCALAPPDATA%/geode/mods/b1rtek.gddlintegration or a similar path)

**Comment by B1rtek** [comment]
I'm guessing that this worked then

**Comment by python-nerd-3** [comment]
> I'm guessing that this worked then

I was gonna try it later but I forgot about it lol.

**Comment by B1rtek** [comment]
did it work?

**Comment by python-nerd-3** [comment]
I'm probably not gonna get to it to be honest

**Comment by python-nerd-3** [comment]
I did it and it didn't worked. Also looked at it in VSCode and it doesn't seem to be corrupted

**Comment by B1rtek** [comment]
A new update was released that adds a button in the mod's settings which resets the cache, hopefully that helps if a similar issue occurrs in the future
