### ISSUE TITLE
Game Crashes when trying to play a level

### ISSUE THREAD

**Issue by MasterGamerY** [B1rtek/Geode-GDDLIntegration#49]
**Describe the bug**
Sometimes, the game crashes when you try to play a level; the crashlog states that this mod is the cause.

**To Reproduce**
Whether the game crashes or not depends on the level. For this crashlog, the level that crashed was this ID: 90922017

**Crash log (from `Geometry Dash/geode/crashlogs`)**
[2024-06-22_00-17-25.log](https://github.com/user-attachments/files/15935093/2024-06-22_00-17-25.log)

**I checked that I have the latest version of this mod**
Yes

**Comment by B1rtek** [comment]
I'm pretty sure it's the same thing as !50, I'm working on a fix rn
