### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Denyscrasav4ik** [B1rtek/Geode-GDDLIntegration#51]
**Describe the bug**
 
**To Reproduce**
1. Open the game
2. Find any demon level on the ladder
3. Open it
4. Congratulations your game died

**Crash log (from `Geometry Dash/geode/crashlogs`)**

Instead of crashlog i have "LastSessionDidCrash" file for some reason

**Additional context**

Maybe its not this mods fault but when I disabled it I stopped crashing. Im mobile

**I checked that I have the latest version of this mod**
Yes

**Comment by B1rtek** [comment]
which level exactly did you open to crash the game

**Comment by Denyscrasav4ik** [comment]
I opened the first level in featured tab (i dont remember its name) and tidal wave

**Comment by B1rtek** [comment]
ok so it's the same thing

**Comment by B1rtek** [comment]
duplicate of #49 and #50, fix incoming very soon
