### ISSUE TITLE
Gddl Integration not loading in gd

### ISSUE THREAD

**Issue by TheRealKozmos** [B1rtek/Geode-GDDLIntegration#54]
**Describe the bug**
Every time I boot up GD it says failed to load GDDL in a small rectangle with a X at the bottom middle of my screen. The tiers of the levels never show up when you click on a demon and instead it just shows the red square with a question mark
**To Reproduce**
1. Load Up Gd
2. See failed to load gddl
3. Click on any demon level
4. Tier doesn't show up 
5. click on the red square and it says Still loading... 
**Crash log (from `Geometry Dash/geode/crashlogs`)**
There is no crash log im pretty sure
**Additional context**

**I checked that I have the latest version of this mod**
Yes i have

**Comment by TheRealKozmos** [comment]
![20240628174950_1](https://github.com/B1rtek/Geode-GDDLIntegration/assets/174152609/7ef918f4-efc2-40ec-9a3e-51943b394f07)
![20240628175026_1](https://github.com/B1rtek/Geode-GDDLIntegration/assets/174152609/30cc6b2d-aa72-443e-8060-0dbace832e61)

**Comment by TheRealKozmos** [comment]
Everytime I Reload gd nothing changes

**Comment by SomeSoggyToast42** [comment]
![image](https://github.com/B1rtek/Geode-GDDLIntegration/assets/96754362/0f055aab-4e90-454b-a463-225e68b9c23b)
Same issue here, only the menu thing is a seperate pop-up and happens roughly a second after going to the main menu.

**Comment by TheRealKozmos** [comment]
Yeah maybe the reason why its different is cuz i have the npesta texture pack, and maybe the reason its happening is a server wide issue idk

**Comment by TeahersAreStupid1234** [comment]
https://i.imgur.com/ZS3eF0N.png

**Comment by TeahersAreStupid1234** [comment]
same issue

**Comment by Octostomp** [comment]
I have the "failed to cache" popup, when using another mod that uses GDDL "Demons In Between" it also fails but it doesn't have the popup, just the little "X Failed to load GDDl" message

**Comment by B1rtek** [comment]
it's because the API is temporarily down, we're having some trouble with it, it's not a mod issue though, I'll keep this open in case you have any more questions about this

**Comment by B1rtek** [comment]
*To every GDDL integration mod user: YES we know it doesn’t work, it is temporary and will be reverted within a week* - Diversion

**Comment by B1rtek** [comment]
The new API is up now, an update to GDDL Integration compatible with it is coming shortly

**Comment by TeahersAreStupid1234** [comment]
Tysm for your help :D

**Comment by TheRealKozmos** [comment]
its updated yay
