### ISSUE TITLE
Could not cache ratings.

### ISSUE THREAD

**Issue by metsor** [B1rtek/Geode-GDDLIntegration#55]
**Describe the bug**
Could not cache ratings from gddladder.com! Check your internet connection and restart game.

**To Reproduce**
 When I open GD I see that it's can't get cache ratings from gddladder.com, and it says that I need to check my internet connection, but connection was okay all time, I've tried to restart game million times but that's not working, i've tried to reinstall it, no one works.. :(

![Screenshot_15](https://github.com/B1rtek/Geode-GDDLIntegration/assets/174329533/69da07d3-9625-41eb-80d3-ca7c9536e85f)

**I checked that I have the latest version of this mod**
Yes

**Comment by B1rtek** [comment]
#54 duplicate
