### ISSUE TITLE
GDDL can't reach gdladder.com

### ISSUE THREAD

**Issue by Ev212** [B1rtek/Geode-GDDLIntegration#57]
Whenever I log onto GD it says it can't reach gdladder.com and can't load any of the GDDl rankings.

1. Go on gd
2. A notification pops up
3. Click on a demon
4. It says ???

This only started happening a few days ago.

**I checked that I have the latest version of this mod**
Yes

**Comment by B1rtek** [comment]
Check the version again, I updated the mod 5 minutes ago

**Comment by Ev212** [comment]
ok

**Comment by AksLolCoding** [comment]
yeah i updated it and its fixed now
