### ISSUE TITLE
Game crashed when opening platformer level

### ISSUE THREAD

**Issue by ZorTik** [B1rtek/Geode-GDDLIntegration#58]
**Describe the bug**
The game crashed while opened platformer level "The Last Wish". However, it did not happen the second time I've opened it, so it may be not that frequent error.

**To Reproduce**
1. Go to featured tab
2. Open "The Last Wish" level page
3. It eventually crashes?

**Crash log (from `Geometry Dash/geode/crashlogs`)**
2024-07-20T12:00:12+0200
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.2.0
Loader Commit: 65ed0d4
Bindings Commit: 103fbd9
Installed mods: 31
Problems: 0

== Exception Information ==
C++ Exception: class std::bad_variant_access("bad variant access")
Faulty Mod: GDDL Integration v1.1.10 (b1rtek.gddlintegration)
Crashed thread: Main

== Stack Trace ==
 - C:\WINDOWS\System32\KERNELBASE.dll + 3b699 (RaiseException + 105)
 - C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll + 5267 (CxxThrowException + 151)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 4d9c9 (std::_Throw_bad_variant_access + 41 | /home/runner/work/geode/geode/.xwin-cache/splat/crt/include/exception:417)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 24894c (matjson::Value::as_int + 28 | /home/runner/work/geode/geode/cpm-cache/json/cdd3528202519ebf1e8a854791f0b86bb35707e7/src/value.hpp:57)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + a508
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 289c5
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 2a89d
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 261bb
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 6114
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 603c
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 72b0b (geode::DefaultEventListenerPool::handle + 491 | /home/runner/work/geode/geode/loader/src/loader/Event.cpp:52)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 117393 (geode::Task<geode::utils::web::WebResponse,geode::utils::web::WebProgress>::finish::<lambda_1>::operator() + 227 | /home/runner/work/geode/geode/loader/include/Geode/loader/../utils/Task.hpp:272)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 85572 (geode::Loader::Impl::executeMainThreadQueue + 242 | /home/runner/work/geode/geode/loader/src/loader/LoaderImpl.cpp:879)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 5e94d (geode::modifier::AsStaticFunction_update<FunctionQueue,void (FunctionQueue::*)(float)>::Impl<void (FunctionQueue::*)(float)>::function + 29 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCScheduler.hpp:115)
 - 000001E520044472 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + bbc24 (cocos2d::CCDirector::drawScene + 36)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + bc33b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 72cd2 (cocos2d::CCApplication::run + 1122)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 23a41a (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:167)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\WINDOWS\System32\KERNEL32.DLL + 17374 (BaseThreadInitThunk + 20)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 4cc91 (RtlUserThreadStart + 33)

== Register States ==
RAX: 0000000000000004
RBX: 0000000000000000
RCX: 0000000000000004
RDX: 00007fffca1cd573
RBP: 0000000000000000
RSP: 000000107a8ffdb0
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ff8311fcc91
R8:  00007fffd0eefc58
R9:  0002002000000005
R10: 0000000000000000
R11: 000000107a8fe9c8
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v1.0.4] absolllute.installer
  | [v8.0.1-alpha.4] absolllute.megahack
x | [v1.2.0] adyagd.ingamelistmod
x | [v0.1.0-alpha.5] alphalaneous.asyncweb
x | [v1.0.1] alphalaneous.is_it_sent
x | [v1.1.10] b1rtek.gddlintegration
x | [v1.0.3] capeling.startpos_switcher
x | [v1.0.6] cdc.level_thumbnails
x | [v4.2.4] cvolton.betterinfo
x | [v1.0.0] cvolton.level-id-api
x | [v1.2.0-beta.2] cvolton.misc_bugfixes
x | [v1.5.1] dankmeme.globed2
x | [v2.0.1] elohmrow.death_tracker
x | [v1.3.4] gdutilsdevs.gdutils
x | [v1.7.1] geode.custom-keybinds
x | [v3.2.0] geode.loader
x | [v1.13.1] geode.node-ids
x | [v1.5.2] hiimjustin000.integrated_demonlist
x | [v1.1.0] hjfod.backups
x | [v1.2.1] hjfod.gmd-api
x | [v1.0.6] jouca.badgesapi
x | [v1.0.3] lilnibblit.chestalert
x | [v1.1.2] mat.run-info
x | [v1.0.0-beta.34] minemaker0430.gddp_integration
x | [v1.4.0-beta.2] oatmealine.ids_integration
x | [v2.1.0] spaghettdev.gd-roulette
x | [v1.0.0] techstudent10.positionswitch
x | [v1.0.0] uproxide.animated_fire
x | [v1.0.0] uproxide.practice_attempts
x | [v1.1.0] xanii.youtubers
x | [v1.2.3] ziegenhainy.xxlify

**Additional context**
As stated above, it did happen only once, so I don't know what can be the cause.

**I checked that I have the latest version of this mod**
Yes

**Comment by B1rtek** [comment]
huh

**Comment by B1rtek** [comment]
v1.1.11 fixes the issue
