### ISSUE TITLE
Game crash when going to newly rated level

### ISSUE THREAD

**Issue by zHackro** [B1rtek/Geode-GDDLIntegration#59]
**Describe the bug**
Title; The game crashes when going to the page of a demon level that has been rated in the past ~minute

**To Reproduce**
1. Wait for a demon level to get rated (can be seen using GDUtils notifications)
2. Go to the newly rated level's page
3. crash

**Crash log (from `Geometry Dash/geode/crashlogs`)**

**Crash 1**

`2024-08-01T20:37:02+0300
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.4.0
Loader Commit: a533b5f
Bindings Commit: de6a02b
Installed mods: 36
Problems: 0

== Exception Information ==
C++ Exception: class std::bad_variant_access("bad variant access")
Faulty Mod: GDDL Integration v1.1.10 (b1rtek.gddlintegration)
Crashed thread: Main

== Stack Trace ==
 - C:\Windows\System32\KERNELBASE.dll + 5fabc (RaiseException + 108)
 - C:\Windows\SYSTEM32\VCRUNTIME140.dll + 5267 (CxxThrowException + 151)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 4dd09 (std::_Throw_bad_variant_access + 41 | /home/runner/work/geode/geode/.xwin-cache/splat/crt/include/exception:417)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 2538ec (matjson::Value::as_int + 28 | /home/runner/work/geode/geode/cpm-cache/json/cdd3528202519ebf1e8a854791f0b86bb35707e7/src/value.hpp:57)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + a508
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 289c5
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 2a89d
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 261bb
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 6114
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 603c
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 72f5b (geode::DefaultEventListenerPool::handle + 491 | /home/runner/work/geode/geode/loader/src/loader/Event.cpp:52)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 119d63 (geode::Task<geode::utils::web::WebResponse,geode::utils::web::WebProgress>::finish::<lambda_1>::operator() + 227 | /home/runner/work/geode/geode/loader/include/Geode/loader/../utils/Task.hpp:275)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 859c2 (geode::Loader::Impl::executeMainThreadQueue + 242 | /home/runner/work/geode/geode/loader/src/loader/LoaderImpl.cpp:879)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 5ec7d (geode::modifier::AsStaticFunction_update<FunctionQueue,void (FunctionQueue::*)(float)>::Impl<void (FunctionQueue::*)(float)>::function + 29 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCScheduler.hpp:115)
 - 00000161A7E84472 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + bbc24 (cocos2d::CCDirector::drawScene + 36)
 - 00000161AAE8D0D2 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 16c758
 - 00000161AAE8D0D2 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + bc33b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 72cd2 (cocos2d::CCApplication::run + 1122)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 2453da (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:167)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\Windows\System32\KERNEL32.DLL + 1257d (BaseThreadInitThunk + 29)
 - C:\Windows\SYSTEM32\ntdll.dll + 5af28 (RtlUserThreadStart + 40)

== Register States ==
RAX: 0000000000000000
RBX: 0000000000000000
RCX: bf037d7cf1000000
RDX: 0000000000000000
RBP: 0000000000000000
RSP: 0000000c004ffbc0
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ff9aa14af28
R8:  00000161b557fce8
R9:  0000016269790360
R10: 00007ff9a7bf4d91
R11: 00000000006500b8
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v8.0.1-alpha.6] absolllute.megahack
x | [v1.2.8] alphalaneous.projectedstars
x | [v1.1.10] b1rtek.gddlintegration
x | [v1.1.2] bitz.customprofiles
  | [v1.0.6] cdc.level_thumbnails
x | [v4.2.5] cvolton.betterinfo
x | [v1.0.0] cvolton.level-id-api
x | [v1.2.0-beta.2] cvolton.misc_bugfixes
x | [v1.5.1] dankmeme.globed2
x | [v2.1.0] elohmrow.death_tracker
x | [v1.0.8] firee.goldenbest
x | [v0.3.0] flafy.autonong
x | [v2.11.0] fleym.nongd
x | [v1.3.7] gdutilsdevs.gdutils
x | [v1.7.1] geode.custom-keybinds
x | [v3.4.0] geode.loader
x | [v1.13.1] geode.node-ids
x | [v1.6.1] geode.texture-loader
x | [v1.1.0] hjfod.backups
x | [v6.7.0] hjfod.betteredit
x | [v1.3.0] hjfod.gdshare
x | [v1.2.1] hjfod.gmd-api
x | [v1.0.0] hjfod.trashcan
x | [v1.0.3] iswilljr.enter-search
x | [v1.2.1] itzkiba.better_progression
x | [v1.1.0] itzkiba.elegant_rankings
x | [v1.2.0] itzkiba.grandpa_demon
x | [v1.0.6] jouca.badgesapi
x | [v1.2.1] mat.run-info
x | [v1.0.0-beta.34] minemaker0430.gddp_integration
x | [v2.0.4-beta.14] muhammadgames.bettermenu
x | [v1.1.2] n.level-pronouns
x | [v2.12.2] techstudent10.discord_rich_presence
x | [v2.3.1] thesillydoggo.gradientpages
  | [v1.5.2] thesillydoggo.qolmod
x | [v1.1.0] xanii.youtubers
`

**Crash 2**

`2024-08-01T20:41:52+0300
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.4.0
Loader Commit: a533b5f
Bindings Commit: de6a02b
Installed mods: 36
Problems: 0

== Exception Information ==
C++ Exception: class std::bad_variant_access("bad variant access")
Faulty Mod: GDDL Integration v1.1.10 (b1rtek.gddlintegration)
Crashed thread: Main

== Stack Trace ==
 - C:\Windows\System32\KERNELBASE.dll + 5fabc (RaiseException + 108)
 - C:\Windows\SYSTEM32\VCRUNTIME140.dll + 5267 (CxxThrowException + 151)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 4dd09 (std::_Throw_bad_variant_access + 41 | /home/runner/work/geode/geode/.xwin-cache/splat/crt/include/exception:417)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 2538ec (matjson::Value::as_int + 28 | /home/runner/work/geode/geode/cpm-cache/json/cdd3528202519ebf1e8a854791f0b86bb35707e7/src/value.hpp:57)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + a508
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 289c5
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 2a89d
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 261bb
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 6114
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\b1rtek.gddlintegration\b1rtek.gddlintegration.dll + 603c
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 72f5b (geode::DefaultEventListenerPool::handle + 491 | /home/runner/work/geode/geode/loader/src/loader/Event.cpp:52)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 119d63 (geode::Task<geode::utils::web::WebResponse,geode::utils::web::WebProgress>::finish::<lambda_1>::operator() + 227 | /home/runner/work/geode/geode/loader/include/Geode/loader/../utils/Task.hpp:275)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 859c2 (geode::Loader::Impl::executeMainThreadQueue + 242 | /home/runner/work/geode/geode/loader/src/loader/LoaderImpl.cpp:879)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 5ec7d (geode::modifier::AsStaticFunction_update<FunctionQueue,void (FunctionQueue::*)(float)>::Impl<void (FunctionQueue::*)(float)>::function + 29 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCScheduler.hpp:115)
 - 0000018AA5CE4472 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + bbc24 (cocos2d::CCDirector::drawScene + 36)
 - 0000018AABBDD0D2 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 16c758
 - 0000018AABBDD0D2 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + bc33b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 72cd2 (cocos2d::CCApplication::run + 1122)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 2453da (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:167)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\Windows\System32\KERNEL32.DLL + 1257d (BaseThreadInitThunk + 29)
 - C:\Windows\SYSTEM32\ntdll.dll + 5af28 (RtlUserThreadStart + 40)

== Register States ==
RAX: 0000000000000000
RBX: 0000000000000000
RCX: 3f20827587000000
RDX: 0000000000000000
RBP: 0000000000000000
RSP: 000000249c5dfc30
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ff9aa14af28
R8:  0000018b268a3a88
R9:  0000018b25a1d360
R10: 00007ff9a7bf4d91
R11: 0000000000cb004d
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v8.0.1-alpha.6] absolllute.megahack
x | [v1.2.8] alphalaneous.projectedstars
x | [v1.1.10] b1rtek.gddlintegration
x | [v1.1.2] bitz.customprofiles
  | [v1.0.6] cdc.level_thumbnails
x | [v4.2.5] cvolton.betterinfo
x | [v1.0.0] cvolton.level-id-api
x | [v1.2.0-beta.2] cvolton.misc_bugfixes
x | [v1.5.1] dankmeme.globed2
x | [v2.1.0] elohmrow.death_tracker
x | [v1.0.9] firee.goldenbest
x | [v0.3.0] flafy.autonong
x | [v2.11.0] fleym.nongd
x | [v1.3.7] gdutilsdevs.gdutils
x | [v1.7.1] geode.custom-keybinds
x | [v3.4.0] geode.loader
x | [v1.13.1] geode.node-ids
x | [v1.6.1] geode.texture-loader
x | [v1.1.0] hjfod.backups
x | [v6.7.0] hjfod.betteredit
x | [v1.3.0] hjfod.gdshare
x | [v1.2.1] hjfod.gmd-api
x | [v1.0.0] hjfod.trashcan
x | [v1.0.3] iswilljr.enter-search
x | [v1.2.1] itzkiba.better_progression
x | [v1.1.0] itzkiba.elegant_rankings
x | [v1.2.0] itzkiba.grandpa_demon
x | [v1.0.6] jouca.badgesapi
x | [v1.2.1] mat.run-info
x | [v1.0.0-beta.35] minemaker0430.gddp_integration
x | [v2.0.4-beta.14] muhammadgames.bettermenu
x | [v1.1.2] n.level-pronouns
x | [v2.12.2] techstudent10.discord_rich_presence
x | [v2.3.1] thesillydoggo.gradientpages
  | [v1.5.2] thesillydoggo.qolmod
x | [v1.1.0] xanii.youtubers
`

**I checked that I have the latest version of this mod**
Yes

**Comment by Paddsladd** [comment]
i have the same issue

**Comment by B1rtek** [comment]
v1.1.11 fixes the issue
